version: '3.3'

services:
  fractions:
    container_name: fractions
    build: .
    ports:
      - '4500:8080'
    restart: always
    volumes:
      - .:/home/node/app
      - website:/home/node/app/build
      - node_modules:/home/node/app/node_modules
    env_file:
      - .env

volumes:
  website:
  node_modules:
