version: '3.3'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - '4600:3000'
    volumes:
      - /home/node/app/node_modules
    restart: on-failure
    container_name: fractions_client
    env_file:
      - .env

  backend:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - '4500:8080'
    restart: on-failure
    container_name: fractions_backend
    volumes:
      - /home/node/app/node_modules
    env_file:
      - .env
